spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 10
      auto-commit: false
      connection-timeout: 3000
    #url: jdbc:postgresql://172.21.0.2:5432/tcc
    url: jdbc:postgresql://localhost:5432/bancotcc
    #url: jdbc:postgresql://localhost:5432/tcc
    username: postgres
    password: 12345678
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  packages-to-scan: br.com.java.tcc.application
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha

#  swagger-ui:
#    tryItOutEnabled: true